### ISSUE TITLE
pyvisa.errors.LibraryError: Error while accessing rsvisa: rsvisa: cannot open shared object file

### ISSUE THREAD

**Issue by JulianPeD** [Rohde-Schwarz/RsInstrument#19]
Hi,
I'd like to connect my HMP2020 to my Raspberry PI (OS: Raspi OS 12 Bookworm, 64bit) via USB Interface and using your Python-lib RSInstrument for measuring voltage & currency of a DUT<br>
I installed all needed packages via **pip install RsInstrument** (Used python: 3.9.13)
Unfortunately I got following while testing the connection....<br>
```
>>> from RsInstrument import *
>>> instr_list = RsInstrument.list_resources('?*', 'rs')
2024-08-08 10:07:44,699 - pyvisa - DEBUG - Could not open VISA wrapper <class 'pyvisa.ctwrapper.highlevel.IVIVisaLibrary'>: rs
Error while accessing rs: rs: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyvisa/ctwrapper/highlevel.py", line 162, in _init
    lib = Library(self.library_path)
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: rs: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/RsInstrument/RsInstrument.py", line 160, in list_resources
    rm = VisaSession.get_resource_manager(visa_select)
  File "/usr/local/lib/python3.9/site-packages/RsInstrument/Internal/VisaSession.py", line 292, in get_resource_manager
    return pyvisa.ResourceManager(visa_select)
  File "/usr/local/lib/python3.9/site-packages/pyvisa/highlevel.py", line 2992, in __new__
    visa_library = open_visa_library(visa_library)
  File "/usr/local/lib/python3.9/site-packages/pyvisa/highlevel.py", line 2904, in open_visa_library
    return cls(argument)
  File "/usr/local/lib/python3.9/site-packages/pyvisa/highlevel.py", line 191, in __new__
    obj._init()
  File "/usr/local/lib/python3.9/site-packages/pyvisa/ctwrapper/highlevel.py", line 164, in _init
    raise errors.LibraryError.from_exception(exc, self.library_path)
pyvisa.errors.LibraryError: Error while accessing rs: rs: cannot open shared object file: No such file or directory
>>> from RsInstrument import *
>>> instr_list = RsInstrument.list_resources('?*')
2024-08-08 10:08:10,330 - pyvisa - DEBUG - No visa library specified, trying to find alternatives.
2024-08-08 10:08:10,331 - pyvisa - DEBUG - Environment variable PYVISA_LIBRARY is unset.
2024-08-08 10:08:10,331 - pyvisa - DEBUG - Not loading dll_extra_paths because we are not on Windows or Python < 3.8
2024-08-08 10:08:10,598 - pyvisa - DEBUG - Automatically found library files: [None, None, None, None, None]
2024-08-08 10:08:10,599 - pyvisa - DEBUG - No user defined library files
2024-08-08 10:08:10,600 - pyvisa - DEBUG - Did not find IVI binary
2024-08-08 10:08:10,600 - pyvisa - DEBUG - Did not find pyvisa-py package
2024-08-08 10:08:10,601 - pyvisa - DEBUG - Could not open VISA wrapper <class 'pyvisa.ctwrapper.highlevel.IVIVisaLibrary'>: rsvisa
Error while accessing rsvisa: rsvisa: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyvisa/ctwrapper/highlevel.py", line 162, in _init
    lib = Library(self.library_path)
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: rsvisa: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/RsInstrument/RsInstrument.py", line 160, in list_resources
    rm = VisaSession.get_resource_manager(visa_select)
  File "/usr/local/lib/python3.9/site-packages/RsInstrument/Internal/VisaSession.py", line 292, in get_resource_manager
    return pyvisa.ResourceManager(visa_select)
  File "/usr/local/lib/python3.9/site-packages/pyvisa/highlevel.py", line 2992, in __new__
    visa_library = open_visa_library(visa_library)
  File "/usr/local/lib/python3.9/site-packages/pyvisa/highlevel.py", line 2904, in open_visa_library
    return cls(argument)
  File "/usr/local/lib/python3.9/site-packages/pyvisa/highlevel.py", line 191, in __new__
    obj._init()
  File "/usr/local/lib/python3.9/site-packages/pyvisa/ctwrapper/highlevel.py", line 164, in _init
    raise errors.LibraryError.from_exception(exc, self.library_path)
pyvisa.errors.LibraryError: Error while accessing rsvisa: rsvisa: cannot open shared object file: No such file or directory
>>>
```

**Comment by minimaga** [comment]
Hello,
Looks like you are missing a VISA backend. You can find one here : https://www.rohde-schwarz.com/us/driver-pages/remote-control/3-visa-and-tools_231388.html

**Comment by sebaleme** [comment]
I had the same issue after installing the pip package with "pip install RsInstrument". I was able to solve this issue by installing the rsvisa debian package:

lsm1so@LE-C-001PN:~$ sudo apt --fix-broken install rsvisa
Reading package lists... Done
Building dependency tree       
Reading state information... Done
rsvisa is already the newest version (5.12.9).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 rsvisa : Depends: libqt5core5a (>= 5.5.0) but it is not going to be installed
          Depends: libqt5gui5 (>= 5.0.2) but it is not going to be installed or
                   libqt5gui5-gles (>= 5.0.2) but it is not going to be installed
          Depends: libqt5widgets5 (>= 5.2.0) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

lsm1so@LE-C-001PN:~$ sudo apt --fix-broken install

lsm1so@LE-C-001PN:~$ sudo apt install rsvisa
Reading package lists... Done
Building dependency tree       
Reading state information... Done
rsvisa is already the newest version (5.12.9).
The following packages were automatically installed and are no longer required:
  gir1.2-snapd-1 guile-2.2-libs libgc1c2 libgnome-games-support-1-3 libgnome-games-support-common libmessaging-menu0 libnatpmp1 libqqwing2v5 libsysmetrics1
  python3-cached-property python3-docker python3-dockerpty python3-docopt python3-texttable usb-modeswitch usb-modeswitch-data
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.

**Comment by Miloslav-RS** [comment]
Hi, sorry for the late response. If it is still an issue, you can always use raw socket communication for which you do not need any VISA installation: https://rsinstrument.readthedocs.io/en/latest/StepByStepGuide.html#no-visa-session
